### ISSUE TITLE
Installation instructions for early adopters

### ISSUE THREAD

**Issue by rizhub** [mediumroast/mr_python#10]
The top page mentions the following. Yet I can't find the early installation for early adopters section
"you should pay attention to section entitled Installation for Early Adopters and Testers."

**Comment by miha42-github** [comment]
Could you not do the pip3 install mediumroast_py?

**Comment by rizhub** [comment]
First time both did not work. Neither pip nor pip3. Not sure why.  It complained about module not recognizable. I assumed it may not be fully released software. Hence tried git+url.  

-rizwan

**Comment by miha42-github** [comment]
Please try again and let me know if the installation works.  If there are dependency problems then we can work through it.

**Comment by miha42-github** [comment]
Old closing
